dataset:
  - type: dali-replay-clip
    args:
      start_min: 2
      end_min: 20
      step_sec: 3
      clip_len: 8
      features: [minimaps]
      minimap_layers: [player_relative, heightMap]
      yields_batch: true
      precalculated_clips: true
      sampler_cfg:
        type: sql
        args:
          database: $ENV:gamedata.db
          filter_query:
            - game_length > 6720
            - read_success = 1
            - parse_success = 1
            - number_game_step > 1024
            - playerAPM > 100
    val_loader:
      type: DALI
      args:
        batch_size: 64
        drop_last: true
    train_loader:
      type: DALI
      args:
        shuffle: true
        batch_size: 64
        drop_last: true
        augmentations:
          - type: permute-dims # FCHW -> FHWC
            args:
              dst: [0, 2, 3, 1]
          - type: random-flip
            args: {}
          - type: random-rotate
            args:
              angle_deg: 180
          - type: permute-dims # FHWC -> FCHW
            args:
              dst: [0, 3, 1, 2]
criterion:
  - type: minimap-bce
    args:
      motion_weight: 2
      motion_version: 2
model:
  - type: residule-unet
    args:
      history_len: 6
      include_heightmap: true
      target: both
      in_layers: both
      deep_supervision: false
      disable_residule: false
      hidden_chs: [32, 64, 128, 256]
    optimizer:
      type: adamw
      args:
        lr: 1.e-3
        gradient_clipping: 0.1
      scheduler:
        type: poly
        args:
          max_iter: 5
          power: 0.9
logger:
  interval: 1000
