dataset:
  - type: dali-replay-clip
    args:
      start_min: 0
      end_min: 120
      step_sec: 3
      clip_len: 8
      features: [minimaps]
      yields_batch: true
      precalculated_clips: true
      sampler_cfg:
        type: sql
        args:
          database: $ENV:gamedata.db
          filter_query:
            - game_length > 6720
            - read_success = 1
            - parse_success = 1
            - number_game_step > 1024
            - playerAPM > 100
    val_loader:
      type: DALI
      args:
        batch_size: 64
        drop_last: true
    train_loader:
      type: DALI
      args:
        shuffle: true
        batch_size: 96
        drop_last: true
        augmentations:
          - type: permute-dims # FCHW -> FHWC
            args:
              dst: [0, 2, 3, 1]
          - type: random-flip
            args: {}
          - type: random-rotate
            args:
              angle_deg: 180
          - type: permute-dims # FHWC -> FCHW
            args:
              dst: [0, 3, 1, 2]
criterion:
  - type: minimap-bce
    args:
      motion_weight: 2
model:
  - type: transformer-v2
    args:
      target: self
      num_latents: 32
      latent_dim: 128
      history_len: 6
      latent_minimap_shape: [6, 6]
      target_in_layers: [heightMap, self, enemy]
      encoder:
        type: image-fpn
        args:
          disable_fpn: true
          hidden_chs: [16, 32, 64, 96]
          strides: [1, 2, 2, 2]
          paddings: [1, 1, 1, 1]
      temporal:
        type: transformer-resampler
        args:
          num_blocks: 4
          num_heads: 8
      decoder_query:
        type: fixed-queries
        args:
          f_num: 16
          f_max: 32
      decoder:
        type: ""
        args:
          num_heads: 4
          out_shape: [128, 128]
    optimizer:
      type: adamw
      args:
        lr: 1.e-4
        gradient_clipping: 0.01
      scheduler:
        type: poly
        args:
          max_iter: 10
          power: 0.9
logger:
  interval: 1000
