apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: sc2-train1
spec:
  maxRetry: 1
  minAvailable: 1
  schedulerName: volcano
  queue: default
  tasks:
    - replicas: 192
      name: serialize
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: dkr-creds
          securityContext:
            runAsUser: 1000
          containers:
            - name: runner
              image: mu00120825.eng.monash.edu.au:5021/sc2-experiments:latest
              command:
                [
                  "python",
                  "-u",
                  "/code/sc2-serializer/scripts/gen_database.py",
                  "--workspace=/mnt/storage",
                 "--workers=8",
                ]
              env:
                - name: DATAPATH
                  value: /mnt/storage/converted/4.9.2/
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              resources:
                requests:
                  memory: 64Gi
                  cpu: 8000m
                limits:
                  memory: 100Gi
                  cpu: 10000m
              volumeMounts:
                - name: storage
                  mountPath: /mnt/storage
                - mountPath: /dev/shm
                  name: dshm
          volumes:
            - name: storage
              nfs:
                server: 130.194.128.238
                path: /mnt/fast/more-users/bryce-rhys
            - name: dshm
              emptyDir:
                medium: Memory
