apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: sc2-conversion
spec:
  maxRetry: 1
  minAvailable: 1
  schedulerName: volcano
  queue: default
  tasks:
    - replicas: 256
      name: serialize
      template:
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: dkr-creds
          securityContext:
            runAsUser: 1000
          containers:
            - name: runner
              image: mu00120825.eng.monash.edu.au:5000/sc2-serializer:latest
              command:
                [
                  ./sc2_converter,
                  --replays=/mnt/storage/4.9.2/,
                  --game=/mnt/storage/SC2/4.9.2/Versions/Base74741/SC2_x64,
                  --converter=action,
                  --partition=/mnt/storage/492_partition/partition,
                  --output=/mnt/storage/converted/4.9.2/db,
                  --badfile=/mnt/storage/converted/4.9.2/badReplays/bad.txt,
                ]
              env:
                - name: SC2PATH
                  value: /mnt/storage/SC2/4.9.2/
                - name: CUDA_VISIBLE_DEVICES
                  value: "-1"
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              resources:
                requests:
                  memory: 2.5Gi
                  cpu: 1000m
                limits:
                  memory: 6Gi
                  cpu: 2000m
              volumeMounts:
                - name: storage
                  mountPath: /mnt/storage
          volumes:
            - name: storage
              nfs:
                server: 130.194.128.238
                path: /mnt/fast/more-users/bryce-rhys
