apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: sc2-scalar-1e-4
spec:
  maxRetry: 1
  minAvailable: 1
  schedulerName: volcano
  queue: default
  tasks:
    - replicas: 1
      name: train
      template:
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: dkr-creds
          securityContext:
            runAsUser: 1000
          nodeSelector:
            nvidia.com/gpu.product: NVIDIA-GeForce-RTX-2080-Ti
          containers:
            - name: runner
              image: mu00120825.eng.monash.edu.au:5000/sc2-experiments:latest
              imagePullPolicy: Always
              command:
                [
                  "python",
                  "/app/outcome_forecast/train.py",
                  "--workspace=/mnt/storage/sc2-minimap-experiments",
                  "--config-file=/mnt/storage/sc2-minimap-experiments/config/scalar-lr-1e-4.yml",
                  "--epoch=50",
                  "--workers=12",
                  "--brief=Scalar lr=1e-4",
                ]
              env:
                - name: DATAPATH
                  value: /mnt/storage/sc2-minimap-subset
              resources:
                requests:
                  memory: 32Gi
                  cpu: 12000m
                  nvidia.com/gpu: 1
                limits:
                  memory: 56Gi
                  cpu: 16000m
                  nvidia.com/gpu: 1
              volumeMounts:
                - name: storage
                  mountPath: /mnt/storage
                - mountPath: /dev/shm
                  name: dshm
          volumes:
            - name: storage
              nfs:
                server: 130.194.128.238
                path: /mnt/fast/more-users/bryce-rhys
            - name: dshm
              emptyDir:
                medium: Memory
