dataset:
  - type: sc2-replay
    args:
      features:
        - minimap_features
        - scalar_features
      timepoints:
        min: 2
        max: 30
        step: 0.5
      min_game_time: 5
    val_loader:
      type: PYTORCH_V1
      args:
        batch_size: 32
        drop_last: true
    train_loader:
      type: PYTORCH_V1
      args:
        shuffle: true
        batch_size: 32
        drop_last: true
criterion:
  - type: win-bce
    args: {}
model:
  - type: win-pred-basic
    args:
      image_enc:
        type: image-v1
        args: {}
      scalar_enc:
        type: scalar-v1
        args: {}
      decoder:
        type: scalar-v1
        args:
          out_ch: 1
    optimizer:
      type: adam
      args:
        step_interval: 1
        lr: 1.e-4
      scheduler:
        type: poly
        args:
          max_iter: 5
          power: 0.9
logger:
  interval: 50
