dataset:
  - type: dali-replay-clip
    args:
      start_min: 2
      end_min: 20
      step_sec: 3
      clip_len: 8
      features: [minimaps]
      yields_batch: true
      precalculated_clips: true
      sampler_cfg:
        type: sql
        args:
          database: $ENV:gamedata.db
          filter_query:
            - game_length > 6720
            - read_success = 1
            - parse_success = 1
            - number_game_step > 1024
            - playerAPM > 100
    val_loader:
      type: DALI
      args:
        batch_size: 64
        drop_last: true
    train_loader:
      type: DALI
      args:
        shuffle: true
        batch_size: 64
        drop_last: true
        augmentations:
          - type: permute-dims # FCHW -> FHWC
            args:
              dst: [0, 2, 3, 1]
          - type: random-flip
            args: {}
          - type: random-rotate
            args:
              angle_deg: 180
          - type: permute-dims # FHWC -> FCHW
            args:
              dst: [0, 3, 1, 2]
criterion:
  - type: minimap-bce
    args:
      motion_weight: 2
model:
  - type: conv-forecast-v2
    args:
      target: both
      encoder:
        type: image-fpn
        args:
          disable_fpn: true
          hidden_chs: [16, 32, 64, 96]
          strides: [1, 2, 2, 2]
          paddings: [1, 1, 1, 1]
      temporal:
        type: temporal-conv
        args:
          hidden_ch: 32
          out_ch: 32
      decoder:
        type: aspp-decoder
        args:
          hidden_ch: 32
          rates: [3, 6, 9]
      last_frame_encoder:
        type: image-fpn
        args:
          disable_fpn: true
          hidden_chs: [16, 32]
          strides: [1, 2]
          paddings: [1, 1]
    optimizer:
      type: adamw
      args:
        lr: 1.e-3
        gradient_clipping: 0.01
      scheduler:
        type: poly
        args:
          max_iter: 10
          power: 0.9
logger:
  interval: 1000
