dataset:
  - type: dali-replay-clip
    args:
      start_min: 2
      end_min: 20
      step_sec: 10
      clip_len: 8
      features: ["minimap_features"]
      should_batch: true
      sampler_cfg:
        type: sql
        args:
          database: $ENV:gamedata.db
          filter_query:
            - game_length > 6720
            - read_success = 1
            - parse_success = 1
            - number_game_step > 512
    val_loader:
      type: DALI
      args:
        batch_size: 64
        drop_last: true
    train_loader:
      type: DALI
      args:
        shuffle: true
        batch_size: 64
        drop_last: true
        augmentations:
          - type: random-rotate
            args:
              angle_deg: 180
criterion:
  - type: minimap-focal
    args: {}
model:
  - type: conv-forecast-v1
    args:
      encoder:
        type: image-fpn
        args:
          output_lvl: 3
          hidden_chs: [16, 32, 64, 96]
          strides: [1, 2, 2, 2]
          paddings: [1, 1, 1, 1]
      temporal:
        type: temporal-conv
        args:
          hidden_ch: 32
          out_ch: 32
      decoder:
        type: aspp-decoder
        args:
          out_ch: 2
          hidden_ch: 32
          rates: [3, 6, 9]
    optimizer:
      type: adamw
      args:
        step_interval: 1
        lr: 1.e-5
        gradient_clipping: 0.01
      scheduler:
        type: poly
        args:
          max_iter: 5
          power: 0.9
logger:
  interval: 10
trainer:
  amp: {}
