dataset:
  - type: dali-folder
    args:
      keys: [valid, minimap_features]
    val_loader:
      type: DALI
      args:
        batch_size: 32
        drop_last: true
    train_loader:
      type: DALI
      args:
        shuffle: true
        batch_size: 16
        drop_last: true
criterion:
  - type: minimap-bce
    args: {}
model:
  - type: conv-forecast-v1
    args:
      encoder:
        type: image-fpn
        args:
          output_lvl: 3
          hidden_chs: [16, 32, 64, 96]
          strides: [1, 2, 2, 2]
          paddings: [1, 1, 1, 1]
      temporal:
        type: temporal-conv
        args:
          hidden_ch: 32
          out_ch: 64
      decoder:
        type: aspp-decoder
        args:
          out_ch: 2
          hidden_ch: 32
          rates: [3, 6, 9]
    optimizer:
      type: adamw
      args:
        step_interval: 1
        lr: 1.e-5
        gradient_clipping: 0.01
      scheduler:
        type: poly
        args:
          max_iter: 5
          power: 0.9
logger:
  interval: 10
trainer:
  amp: {}
