dataset:
  - type: dali-replay-clip
    args:
      start_min: 2
      end_min: 20
      step_sec: 10
      clip_len: 8
      features: ["minimap_features"]
      yields_batch: true
      sampler_cfg:
        type: sql
        args:
          database: $ENV:gamedata.db
          filter_query:
            - game_length > 6720
            - read_success = 1
            - parse_success = 1
            - number_game_step > 512
    val_loader:
      type: DALI
      args:
        batch_size: 128
        drop_last: true
    train_loader:
      type: DALI
      args:
        shuffle: true
        batch_size: 128
        drop_last: true
        augmentations:
          - type: permute-dims # FCHW -> FHWC
            args:
              dst: [0, 2, 3, 1]
          - type: random-flip
            args: {}
          - type: random-rotate
            args:
              angle_deg: 180
          - type: permute-dims # FHWC -> FCHW
            args:
              dst: [0, 3, 1, 2]
criterion:
  - type: minimap-focal
    args: {}
model:
  - type: transformer-forecast-v1
    args:
      num_latents: 32
      latent_dim: 128
      latent_minimap_shape: [6, 6]
      encoder:
        type: image-fpn
        args:
          disable_fpn: true
          hidden_chs: [16, 32, 64, 96]
          strides: [1, 2, 2, 2]
          paddings: [1, 1, 1, 1]
      temporal:
        type: transformer-resampler
        args:
          num_blocks: 4
          num_heads: 8
      decoder_query:
        type: fixed-queries
        args:
          f_num: 16
          f_max: 32
      decoder:
        type: ""
        args:
          num_heads: 4
          output_dim: 2
          out_shape: [128, 128]
    optimizer:
      type: adamw
      args:
        step_interval: 1
        lr: 1.e-5
        gradient_clipping: 0.01
      scheduler:
        type: poly
        args:
          max_iter: 100
          power: 0.9
logger:
  interval: 1000
trainer:
  amp: {}
  validation_interval: 10000
checkpointer:
  mode: iteration
  latest: 10000
  extra: 50000
