apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: sc2-database
spec:
  maxRetry: 1
  minAvailable: 1
  schedulerName: volcano
  queue: default
  tasks:
    - replicas: 64
      name: create
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: dkr-creds
          securityContext:
            runAsUser: 1000
          containers:
            - name: runner
              image: mu00120825.eng.monash.edu.au:5000/sc2-experiments:master
              imagePullPolicy: Always
              command:
                [
                  python3,
                  -u,
                  /app/database_tools/gen_database.py,
                  main,
                  --workspace=/mnt/storage/converted/new-db,
                  --workers=8,
                  --pod-offset=192,
                ]
              env:
                - name: DATAPATH
                  value: /mnt/storage/converted/4.9.2/
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              resources:
                requests:
                  memory: 48Gi
                  cpu: 8000m
                limits:
                  memory: 64Gi
                  cpu: 10000m
              volumeMounts:
                - name: storage
                  mountPath: /mnt/storage
                - name: dshm
                  mountPath: /dev/shm
          volumes:
            - name: storage
              nfs:
                server: 130.194.128.238
                path: /mnt/fast/more-users/bryce-rhys
            - name: dshm
              emptyDir:
                medium: Memory
